package com.example.airqualilty.Selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchForCityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchForCity() {
    driver.get("http://localhost:8084/CityInfo/8373/");
    driver.manage().window().setSize(new Dimension(1853, 1053));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".leaflet-layer:nth-child(2) .leaflet-tile:nth-child(1)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("AirQuality"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("input-station")).click();
    driver.findElement(By.id("input-station")).sendKeys("Porto");
    driver.findElement(By.cssSelector(".container:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".container:nth-child(6)")).click();
    driver.findElement(By.linkText("8373")).click();
  }
}
